// Automatically generated by interface_generator.pl
// Interface name: irsi2c
// Interface definition: ../rtl/irsi2c_interface.def
// Generation date/time: Thu Mar 8, 2012 21:12:17
`define IRSI2CIF_SIZE 7
