// Automatically generated by interface_generator.pl
// Interface name: irsi2c
// Interface definition: ../rtl/irsi2c_interface.def
// Generation date/time: Thu Mar 8, 2012 21:12:17

/*
 * IRS-to-I2C controller interface.
 * 
 * The IRS module occasionally needs to tell the I2C controller
 * to do something. Right now this only involves issuing the
 * GPIO initialization.
*/

`include "irsi2c_interface.vh"
// BEGIN irsi2c irsi2c_irs DATE Thu Mar 8, 2012 21:12:17
// 
// wire irs_clk_o;
// wire i2c_clk_i;
// wire irs_init_o;
// wire [1:0] gpio_o;
// wire [1:0] gpio_ack_i;
// irsi2c_irs irsi2cif(.interface_io(interface_io),
//                     .irs_clk_i(irs_clk_o),
//                     .i2c_clk_o(i2c_clk_i),
//                     .irs_init_i(irs_init_o),
//                     .gpio_i(gpio_o),
//                     .gpio_ack_o(gpio_ack_i));
//
// END irsi2c irsi2c_irs DATE Thu Mar 8, 2012 21:12:17

module irsi2c_irs(
		inout [`IRSI2CIF_SIZE-1:0] interface_io,
		input  irs_clk_i,
		output  i2c_clk_o,
		input  irs_init_i,
		input  [1:0]  gpio_i,
		output  [1:0]  gpio_ack_o
		);

	assign interface_io[0] = irs_clk_i;
	assign i2c_clk_o = interface_io[1];
	assign interface_io[2] = irs_init_i;
	assign interface_io[4:3] = gpio_i;
	assign gpio_ack_o = interface_io[6:5];

endmodule


//% Reassigns a irsi2c interface from a irsi2c_irs on A_i
module irsi2c_irs_reassign( A_i, B_o );
	inout [`IRSI2CIF_SIZE-1:0] A_i;
	inout [`IRSI2CIF_SIZE-1:0] B_o;

	assign B_o[0] = A_i[0];
	assign A_i[1] = B_o[1];
	assign B_o[2] = A_i[2];
	assign B_o[4:3] = A_i[4:3];
	assign A_i[6:5] = B_o[6:5];
endmodule

// BEGIN irsi2c irsi2c_i2c DATE Thu Mar 8, 2012 21:12:17
// 
// wire irs_clk_i;
// wire i2c_clk_o;
// wire irs_init_i;
// wire [1:0] gpio_i;
// wire [1:0] gpio_ack_o;
// irsi2c_i2c irsi2cif(.interface_io(interface_io),
//                     .irs_clk_o(irs_clk_i),
//                     .i2c_clk_i(i2c_clk_o),
//                     .irs_init_o(irs_init_i),
//                     .gpio_o(gpio_i),
//                     .gpio_ack_i(gpio_ack_o));
//
// END irsi2c irsi2c_i2c DATE Thu Mar 8, 2012 21:12:17

module irsi2c_i2c(
		inout [`IRSI2CIF_SIZE-1:0] interface_io,
		output  irs_clk_o,
		input  i2c_clk_i,
		output  irs_init_o,
		output  [1:0]  gpio_o,
		input  [1:0]  gpio_ack_i
		);

	assign irs_clk_o = interface_io[0];
	assign interface_io[1] = i2c_clk_i;
	assign irs_init_o = interface_io[2];
	assign gpio_o = interface_io[4:3];
	assign interface_io[6:5] = gpio_ack_i;

endmodule


//% Reassigns a irsi2c interface from a irsi2c_i2c on A_i
module irsi2c_i2c_reassign( A_i, B_o );
	inout [`IRSI2CIF_SIZE-1:0] A_i;
	inout [`IRSI2CIF_SIZE-1:0] B_o;

	assign A_i[0] = B_o[0];
	assign B_o[1] = A_i[1];
	assign A_i[2] = B_o[2];
	assign A_i[4:3] = B_o[4:3];
	assign B_o[6:5] = A_i[6:5];
endmodule

// BEGIN irsi2c irsi2c_debug DATE Thu Mar 8, 2012 21:12:17
// 
// wire irs_clk_i;
// wire i2c_clk_i;
// wire irs_init_i;
// wire [1:0] gpio_i;
// wire [1:0] gpio_ack_i;
// irsi2c_debug irsi2cif(.interface_io(interface_io),
//                       .irs_clk_o(irs_clk_i),
//                       .i2c_clk_o(i2c_clk_i),
//                       .irs_init_o(irs_init_i),
//                       .gpio_o(gpio_i),
//                       .gpio_ack_o(gpio_ack_i));
//
// END irsi2c irsi2c_debug DATE Thu Mar 8, 2012 21:12:17

module irsi2c_debug(
		inout [`IRSI2CIF_SIZE-1:0] interface_io,
		output  irs_clk_o,
		output  i2c_clk_o,
		output  irs_init_o,
		output  [1:0]  gpio_o,
		output  [1:0]  gpio_ack_o
		);

	assign irs_clk_o = interface_io[0];
	assign i2c_clk_o = interface_io[1];
	assign irs_init_o = interface_io[2];
	assign gpio_o = interface_io[4:3];
	assign gpio_ack_o = interface_io[6:5];

endmodule


