// Automatically generated by interface_generator.pl
// Interface name: irswb
// Interface definition: irswb_interface.def
// Generation date/time: Tue Mar 27, 2012 20:57:43
`define IRSWBIF_SIZE 73
