// Automatically generated by interface_generator.pl
// Interface name: wb
// Interface definition: ../rtl/wb_interface.def
// Generation date/time: Fri Mar 9, 2012 13:52:41
`define WBIF_SIZE 40
